-- Esquema de WebFit. La API lo crea sola la primera vez;
-- este archivo sirve para importarlo a mano desde phpMyAdmin si se prefiere.

CREATE TABLE IF NOT EXISTS meta (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profile (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  height_cm DECIMAL(5,1) NOT NULL,
  start_weight_kg DECIMAL(5,2) NOT NULL,
  kcal_floor SMALLINT UNSIGNED NOT NULL,
  kcal_target SMALLINT UNSIGNED NOT NULL,
  protein_target SMALLINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meals (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  label VARCHAR(80) NOT NULL,
  anchor VARCHAR(80) NOT NULL DEFAULT '',
  kcal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  protein SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS weights (
  `date` DATE NOT NULL PRIMARY KEY,
  kg DECIMAL(5,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS intake (
  `date` DATE NOT NULL PRIMARY KEY,
  extra_kcal MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  extra_protein MEDIUMINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS intake_meals (
  `date` DATE NOT NULL,
  meal_id VARCHAR(32) NOT NULL,
  PRIMARY KEY (`date`, meal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
  `date` DATE NOT NULL PRIMARY KEY,
  `day` CHAR(1) NOT NULL,
  notes TEXT NULL,
  created_at BIGINT UNSIGNED NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS session_sets (
  session_date DATE NOT NULL,
  exercise_id VARCHAR(40) NOT NULL,
  set_index TINYINT UNSIGNED NOT NULL,
  weight DECIMAL(6,2) NOT NULL DEFAULT 0,
  reps SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (session_date, exercise_id, set_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS adjustments (
  week_key DATE NOT NULL PRIMARY KEY,
  delta_kg DECIMAL(5,2) NOT NULL DEFAULT 0,
  proposed_kcal MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  previous_kcal MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  decision VARCHAR(10) NOT NULL DEFAULT 'dismissed',
  decided_at BIGINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS backups (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  revision BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL,
  payload MEDIUMTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reminders (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  label VARCHAR(80) NOT NULL,
  `time` TIME NOT NULL,
  days VARCHAR(20) NOT NULL DEFAULT '0,1,2,3,4,5,6',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  kind VARCHAR(16) NOT NULL DEFAULT 'other',
  detail VARCHAR(160) NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO meta (id, revision, updated_at) VALUES (1, 0, UTC_TIMESTAMP());
